types:
  features:
    - name: hbond-hyd
      type: arrow
      drawopts:
        color: [0.8, 0.0, 0.0]
        radius: 0.25
        length: 1.8
      adjopts:
        radii: 1.55

    - name: hbond-acc
      type: arrow
      drawopts:
        color: [0.0, 0.0, 0.8]
        radius: 0.25
        length: 1.8
      adjopts:
        radii: 1.2

    # - name: ionizable-neg
    #   type: sphere

    # - name: ionizable-pos
    #   type: sphere

    - name: aromatic-pi
      type: arrow
      drawopts:
        color: [0.0, 0.7, 0.1]
        radius: 0.25
        length: 1.8
      adjopts:
        dist: 4.0
        radii: 1.5

    - name: hydrophobic
      type: sphere
      drawopts:
        color: [0.2, 0.7, 0.0]
        radius: 0.0 # means to show the actual featurized radius
        opacity: 0.2 # not working...
  
  pairs:
    distance:
      auto: True
      disable:
        - hydrophobic|distance|hydrophobic
      modify: {}

    manual: []
      # - name: hbond-acc|distance|hbond-acc
      #   fts: [hbond-acc, hbond-acc]
      #   type: distance # angle(aa)
      
      # - name: hbond-acc|distance|hydrophobic
      #   fts: [hbond-acc, hydrophobic]
      #   type: distance # angle(aa)

patterns:
  - name: HPolar
    smarts: "[#1;$(*-[O,N,S])]"
    variables:
      - keys: [v1]
        func: direction
        values: [n(0)-0, 0]
    features:
      - type: hbond-hyd
        point: 0
        direction: v1
        radius: 0.0
  
  - name: (O|N-|S)=RR2
    smarts: "[O,N-,Sv2;$(*=**)]"
    variables:
      - keys: [v1, v2]
        func: eplane3
        values: [0, n(0)-0, nn(0)-0-0]
    features:
      - type: hbond-acc
        point: [0, 0]
        direction: [v1, v2]
        radius: [0.0, 0.0]
  
  - name: R(O|N-|S)R
    smarts: "[O,N-,Sv2;$(*(-*)-*)]"
    variables:
      - keys: [v1, v2]
        func: tetrahedral3
        values: [0, n(0)-0, n(0)-1]
    features:
      - type: hbond-acc
        point: [0, 0]
        direction: [v1, v2]
        radius: [0.0, 0.0]
  
  - name: (O-|S-)
    smarts: "[Ov1-,Sv1-;$(**)]"
    variables:
      - keys: [p1]
        func: angle2-point
        values: [0, n(0)-0]
        extra:
          angle: 109.5
      - keys: [v1]
        func: direction
        values: [0, p1]
      - keys: [v2, v3]
        func: tetrahedral3
        values: [0, n(0)-0, p1]
    features:
      - type: hbond-acc
        point: [0, 0, 0]
        direction: [v1, v2, v3]
        radius: [0.0, 0.0, 0.0]
  
  - name: R(O|N-|S,Arom)R
    smarts: "[o,n-,sv2;$(*(:*):*)]"
    variables:
      - keys: [v1]
        func: plane3
        values: [0, n(0)-0, n(0)-1]
    features:
      - type: hbond-acc
        point: 0
        direction: v1
        radius: 0.0

  - name: N#C
    smarts: "[$(N#C*)]"
    variables:
      - keys: [v1]
        func: direction
        values: [n(0)-0, 0]
    features:
      - type: hbond-acc
        point: 0
        direction: v1
        radius: 0.0

  - name: Arom5
    smarts: "a1aaaa1"
    variables:
      - keys: [v1]
        func: perpendicular3
        values: [0, 1, 2]
      - keys: [v2]
        func: minus
        values: [v1]
      - keys: [center]
        func: mean
        values: [0, 1, 2, 3, 4]
    features:
      - type: aromatic-pi
        point: [center, center]
        direction: [v1, v2]
        radius: [0.0, 0.0]

  - name: CH3
    smarts: "[CH3]"
    features:
      - type: hydrophobic
        point: 0
        radius: 1.1
    
        